### ISSUE TITLE
Яндекс.Практикум:Код-ревью

### ISSUE THREAD

**Issue by zlocate** [Alexandr-exe/validation_form#2]
Добрый вечер. Благодарю за проделанную работу.
К сожалению, текущая реализация содержит ряд недостатков не позволяющих мне засчитать ее на данной итерации:

## Репозиторий
**Нужно исправить** заголовок должен включать в себя информацию отражающую назначение \ наименование проекта
**Можно лучше**: Добавить .gitignore.
.gitignore должен содержать правила, исключающие попадание временных и\или системных файлов в репозиторий.
В случае если вы затрудняетесь с составлением списка базовых правил можете воспользоваться сервисом-генератором, например gitignore.io

## Регулярные выражения
**Можно лучше** Квантификатор `{1}` можно не использовать. Он не играет никакой роли.
**Можно лучше** Квантификатор `{1,}` можно заменить на `+` - он означает "один или более"
Подробнее о квантификаторах: https://learn.javascript.ru/regexp-quantifiers

### Email
**Нужно исправить** следующие корректные кейсы не проходят валидацию
`denis_zlocate@gmail.academy` - имя пользователя может включать в себя одиночный (подряд) подчерк
`some-extra-long-name@some.extra.long.domain.name` - адрес может включать в себя произвольное число поддоменов.
**Нужно исправить** следующие некорректные кейсы проходят валидацию
`my---mail@site.ru` - адрес электронной почты, содержащий несколько символов '-' подряд является некорректным

### Адрес сайта
**Нужно исправить** необходимо исключить список разрешенных доменных зон из регулярного выражения
Адрес с любой корректной доменной зоной должен проходить проверку (при условии, что он не содержит запрещенных компонентов в других частях)

**Comment by Alexandr-exe** [comment]
###  Всё исправленно,
Я прада не понял,первого замечания:
**- Нужно исправить заголовок должен включать в себя информацию отражающую назначение \ наименование проекта.**
Если это про названия репозитория, то не понимаю, чем не устраивает form.   у 60% группы так называется(у которых приняли работу.)

**Comment by zlocate** [comment]
> ### Всё исправленно,
> Я прада не понял,первого замечания:
> **- Нужно исправить заголовок должен включать в себя информацию отражающую назначение \ наименование проекта.**
> Если это про названия репозитория, то не понимаю, чем не устраивает form. у 60% группы так называется(у которых приняли работу.)

Добрый вечер. Прошу прощения за размытую формулировку. Речь шла о заголовке в README :)
Судя по всему информацию оперативно дошла до вас через наставника :)

**Comment by zlocate** [comment]
К сожалению остается кейс, требующий проработки
### Email
**Нужно исправить** следующие корректные кейсы не проходят валидацию
`some@mail-domain.ru` - доменное имя может включать в себя одиночный (подряд) символ тире (`-`)
После его исправления работа будет принята

**Comment by Alexandr-exe** [comment]
### Исправления сделаны
#### Поддомены тоже могут иметь тире(-)
#### (Если бы, сразу написали,сделал при первой переделке)
--
А почему патерны отличаются по ТЗ и по реалиям? Я понимаю, что это всё должно быть, но можно было тогда не давать какие примеры должны валидироваться в задании(Если не в курсе, у нас есть определённый список который должен валидироваться:)).Я понимаю что это не к вам, просто мысли в слух)

**Comment by zlocate** [comment]
> ### Исправления сделаны
> #### Поддомены тоже могут иметь тире(-)
> #### (Если бы, сразу написали,сделал при первой переделке)
> --
> А почему патерны отличаются по ТЗ и по реалиям? Я понимаю, что это всё должно быть, но можно было тогда не давать какие примеры должны валидироваться в задании(Если не вL курсе, у нас есть определённый список который должен валидироваться:)).Я понимаю что это не к вам, просто мысли в слух)

Вопрос хороший и уместный. Про список позитивных кейсов в задании я в курсе, также как и про формулировку задания.
Причины 2:
1. Для полей url и email ввиду вариантивности каждой из частей сложно составить компактный список покрывающий все кейсы. Постепенно силами команды контента и ревьюверов он пополняется (например текущие тест-кейсы в задании это выдержка из моего персонального листа кейсов).
Мы стараемся не захламлять его очевидными и примерами и расширяем его когда видим что у студентов тот или иной сценарий часто "западает".

2. Отсутствие в текущей версии негативных сценариев. Я думаю вы обратили внимание, что в текущей версии отсутствуют негативные сценарии (примеры, которые НЕ должны проходить валидацию). Меж тем это достаточно важный критерий. Также рассчитываем в ближайшее время расширить задание и по этой части.

Я прекрасно понимаю ваш дискомфорт от дополнительных итераций, которых могло бы не быть в случае если все кейсы были бы вам известны заранее. 
К сожалению, в текущий реалиях часть из них приходится озвучивать ревьюверам :(
Благодарю вас за понимание.

**Comment by zlocate** [comment]
Кстати мы за любой фидбэк, хоть это и не совсем по нашей части (основной объем обратной связи идет от наставников)
И если что-то показалось сложным \ странным \ подставить свое - пишите, я постараюсь оперативно донести до команды

**Comment by zlocate** [comment]
Работа принята. Желаю успехов в дальнейшем прохождении курса.

**Comment by Alexandr-exe** [comment]
#### Спасибо, будем стараться.

### По поводу фидбэков. только емаил,можно было за место шаблонов, примерное расписать словами.

_Например_:
--
`user@domain.ru` - где `_user_` это _имя_ почтового ящика, `_domain_` это _домен_ почтового сервиса

_Имя_ пользователя может содержать одиночные _" - "_  , не ограниченное число раз, 
или нижнее подчёркивания  _" _ "_, не ограниченное число раз
`user-user@domain.ru`, `user_user@domain.ru`

_Домен_ может содержать одиночные _" - "_  , не ограниченное число раз, 
`user@domain-domain.ru`

так же домены могут включать поддомены, не ограниченное число, 
`user@domain.domain.ru`

#### done
---
Как то так, так было бы более понятнее что нужно, а как сейчас это похоже на формулировку типа 
-"Вот шаблоны,только они."

**Comment by zlocate** [comment]
> #### Спасибо, будем стараться.
> ### По поводу фидбэков. только емаил,можно было за место шаблонов, примерное расписать словами.
> ## _Например_:
> `user@domain.ru` - где `_user_` это _имя_ почтового ящика, `_domain_` это _домен_ почтового сервиса
> 
> _Имя_ пользователя может содержать одиночные _" - "_ , не ограниченное число раз,
> или нижнее подчёркивания _" _ "_, не ограниченное число раз
> `user-user@domain.ru`, `user_user@domain.ru`
> 
> _Домен_ может содержать одиночные _" - "_ , не ограниченное число раз,
> `user@domain-domain.ru`
> 
> так же домены могут включать поддомены, не ограниченное число,
> `user@domain.domain.ru`
> 
> #### done
> Как то так, так было бы более понятнее что нужно, а как сейчас это похоже на формулировку типа
> -"Вот шаблоны,только они."

Благодарю. Передал ваше пожелание :)
